id: icu-issue-23002
project: icu
sanitizer: UndefinedBehaviorSanitizer
type: Integer Overflow
binary: poc
trigger_commit: ed69e5336d0710141a3ca5ce566896753d87bbbf
patch:
  commit: 93ce388619357ce96cc832212ede80ae30d9e9a4
  date: '2025-01-03T15:48:24-08:00'
reference:
- https://github.com/unicode-org/icu
- https://unicode-org.atlassian.net/browse/ICU-23002
- https://github.com/unicode-org/icu/commit/ed69e5336d0710141a3ca5ce566896753d87bbbf
- https://github.com/unicode-org/icu/commit/93ce388619357ce96cc832212ede80ae30d9e9a4
