id: vim-gh-16606
project: vim
sanitizer: AddressSanitizer
type: Heap Buffer Overflow
binary: vim
trigger_commit: 97baa1cfe83c08eff1a452aca8d91f51112ca932
patch:
  commit: c5654b84480822817bb7b69ebc97c174c91185e9
  date: '2025-02-10T21:12:19+01:00'
reference:
- https://github.com/vim/vim
- https://github.com/vim/vim/issues/16606
- https://github.com/vim/vim/commit/97baa1cfe83c08eff1a452aca8d91f51112ca932
- https://github.com/vim/vim/commit/c5654b84480822817bb7b69ebc97c174c91185e9
