id: jq-gh-2825
project: jq
sanitizer: AddressSanitizer
type: Heap Buffer Overflow
binary: jq
trigger_commit: f86566b2631b777c0d0c9a4572eb21146a14829b
patch:
  commit: 3fa10e8cc197390392f5f5f6e0c9e2fcd5590530
  date: '2023-08-13T14:17:25+02:00'
reference:
- https://github.com/jqlang/jq
- https://github.com/jqlang/jq/issues/2825
- https://github.com/jqlang/jq/commit/f86566b2631b777c0d0c9a4572eb21146a14829b
- https://github.com/jqlang/jq/commit/3fa10e8cc197390392f5f5f6e0c9e2fcd5590530
