id: xml-commit-db07dd6
project: libxml2
sanitizer: AddressSanitizer
type: Heap Buffer Overflow
binary: xmllint
trigger_commit: cbb271655cadeb8dbb258a64701d9a3a0c4835b4
patch:
  commit: db07dd613e461df93dde7902c6505629bf0734e9
  date: '2016-05-23T15:01:07+08:00'
reference:
- https://gitlab.gnome.org/GNOME/libxml2
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/cbb271655cadeb8dbb258a64701d9a3a0c4835b4
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/db07dd613e461df93dde7902c6505629bf0734e9
