id: v8-regress-1427932
project: v8
sanitizer: V8Sanitizer
type: Reachable Assertion
trigger_commit: fe1ba4fe470f5dbd697e556375bda38e43255447
binary: d8
patch:
  commit: 697545f4c295acc8c983cf4a6b8cd3fe221a871b
  date: 2023-04-13 15:32:36+00:00
reference:
- https://chromium.googlesource.com/v8/v8.git
- https://chromium.googlesource.com/v8/v8.git/+/fe1ba4fe470f5dbd697e556375bda38e43255447
- https://chromium.googlesource.com/v8/v8.git/+/697545f4c295acc8c983cf4a6b8cd3fe221a871b
