id: xml-commit-45752d2
project: libxml2
sanitizer: AddressSanitizer
type: Use After Free
binary: xmllint
trigger_commit: a820dbeac29d330bae4be05d9ecd939ad6b4aa33
patch:
  commit: 45752d2c334b50016666d8f0ec3691e2d680f0a0
  date: '2016-05-23T15:01:07+08:00'
reference:
- https://gitlab.gnome.org/GNOME/libxml2
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/a820dbeac29d330bae4be05d9ecd939ad6b4aa33
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/45752d2c334b50016666d8f0ec3691e2d680f0a0
