id: php-gh-12721
project: php
sanitizer: LeakAddressSanitizer
type: NULL Pointer Dereference
trigger_commit: f90b40416ffa731f19e8a9a9674ea4a8ab43fe5d
binary: php
patch:
  commit: 4d41dffb4f355872476bae561264c4796eef26b8
  date: '2023-11-19T11:52:27+01:00'
reference:
- https://github.com/php/php-src.git
- https://github.com/php/php-src/issues/12721
- https://github.com/php/php-src/commit/f90b40416ffa731f19e8a9a9674ea4a8ab43fe5d
- https://github.com/php/php-src/commit/4d41dffb4f355872476bae561264c4796eef26b8
