id: py-pr-102397
project: cpython
sanitizer: AddressSanitizer
type: Race Condition
trigger_commit: 8bf8e3d9a001f1d955a9f0875ac5a70f6d5a5f5c
binary: python
patch:
  commit: 7905ae7b1a347a5dd15174f7e44bb67c4cdb5972
  date: '2023-03-08T00:26:20-08:00'
reference:
- https://github.com/python/cpython.git
- https://github.com/python/cpython/pull/102528
- https://github.com/python/cpython/issues/102397
- https://github.com/python/cpython/commit/8bf8e3d9a001f1d955a9f0875ac5a70f6d5a5f5c
- https://github.com/python/cpython/commit/7905ae7b1a347a5dd15174f7e44bb67c4cdb5972
