id: xml-commit-f4029cd
project: libxml2
sanitizer: UndefinedBehaviorSanitizer
type: Integer Overflow
binary: xmllint
trigger_commit: a58331a6ee4d4c161cebfa4e0d9a090945c6bf23
patch:
  commit: f4029cd413940677a310b48cd6cf6acf9cf33008
  date: '2017-05-31T16:04:37+02:00'
reference:
- https://gitlab.gnome.org/GNOME/libxml2
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/a58331a6ee4d4c161cebfa4e0d9a090945c6bf23
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/f4029cd413940677a310b48cd6cf6acf9cf33008
