id: xml-gh-932
project: libxml2
sanitizer: LeakAddressSanitizer
type: NULL Pointer Dereference
binary: poc
trigger_commit: 069bcda17d8194e9582c64dd4bc9dac99b015810
patch:
  commit: 499bcb78ab389f60c2fd634ce410d4bb85c18765
  date: '2025-07-04T09:35:14+00:00'
reference:
- https://gitlab.gnome.org/GNOME/libxml2
- https://gitlab.gnome.org/GNOME/libxml2/-/merge_requests/932
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/069bcda17d8194e9582c64dd4bc9dac99b015810
- https://gitlab.gnome.org/GNOME/libxml2/-/commit/499bcb78ab389f60c2fd634ce410d4bb85c18765
