id: vim-gh-16796
project: vim
sanitizer: AddressSanitizer
type: Heap Buffer Overflow
binary: vim
trigger_commit: a95085e0fc2e46c7136982e8ba1ae91375991bfd
patch:
  commit: 3ed6659549e447ff00def8edc841321e497f70a8
  date: '2025-03-05T20:05:18+01:00'
reference:
- https://github.com/vim/vim
- https://github.com/vim/vim/issues/16796
- https://github.com/vim/vim/commit/a95085e0fc2e46c7136982e8ba1ae91375991bfd
- https://github.com/vim/vim/commit/3ed6659549e447ff00def8edc841321e497f70a8
