id: hdf5-gh-5296
project: hdf5
sanitizer: AddressSanitizer
type: NULL Pointer Dereference
binary: poc
trigger_commit: 354994a91acc5bfd41d5f2519514261615be8d5d
patch:
  commit: e8760978c93c9d68fa8d250245162d9faaab0821
  date: '2025-02-07T09:44:01-06:00'
reference:
- https://github.com/HDFGroup/hdf5
- https://github.com/HDFGroup/hdf5/issues/5296
- https://github.com/HDFGroup/hdf5/commit/354994a91acc5bfd41d5f2519514261615be8d5d
- https://github.com/HDFGroup/hdf5/commit/e8760978c93c9d68fa8d250245162d9faaab0821
